### ISSUE TITLE
Optimizing Images 

### ISSUE THREAD

**Issue by NikhilDoWhile** [loreanvictor/connect-platform#5]
Properly formatting and compressing images can save many bytes of data.
Reduction of 84.9KiB (50% reduction)

**Source**: PageSpeed Insights
Below are compressed images:

shot1.png ( 59.9KB --> 27.3KB )
![shot1](https://user-images.githubusercontent.com/9911561/39214542-7536755c-4832-11e8-8554-5299b4a65c73.png)

shot2.png ( 107KB --> 54.3KB)
![shot2](https://user-images.githubusercontent.com/9911561/39214543-757769c2-4832-11e8-92b8-456c3967f487.png)

**Comment by loreanvictor** [comment]
Thanks for the suggestion again! It is of course not a priority to optimize the Github Page, however if I was to fix this specific one, don't you think replacing ".png" images with ".svg" ones would be far a better optimization?

**Comment by loreanvictor** [comment]
since this is not a priority right now I will be closing this issue.
