### ISSUE TITLE
Optimization Suggestion: Eliminate render-blocking

### ISSUE THREAD

**Issue by NikhilDoWhile** [loreanvictor/connect-platform#6]
Eliminate render-blocking JavaScript and CSS in above-the-fold content.

**In inedx.html, line 7:**

`<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>`

**Note:** 

- If the "src" attribute is present, the <script> element must be empty.
- If async is not present and defer="defer": The script is executed when the page has finished parsing

eg:
If the HTML document looks like this
```
<head>
    <script type="text/javascript" src="small.js"></script>
</head>
```
Then you can inline the script as follows:
```
<script type="text/javascript">
      /* contents of a small JavaScript file */
</script>
```

**Source**: PageSpeed Insights
**Reference**: 
https://developers.google.com/speed/docs/insights/BlockingJS
https://www.w3schools.com/tags/tag_script.asp

**Comment by loreanvictor** [comment]
Thanks for the suggestions. However, optimizing the GitHub page is not a priority at the moment. It would of course be extremely cool of you if you could resolve this issue and create a pull request for it, although I would suggest taking a look at the rest of the code along other issues as well as they bear more pressing matters at the moment.

Further discussion on this matter better be moved over the pull request (if any) that intends to fix it, so I will close this for now.
